// Service to generate AI-based study plans
import { db } from './db.js';

export async function generateStudyPlan(userId, subjectsUnits, deadline) {
  // Find user to check for Gemini API key
  const user = db.findOne('users', { id: userId });
  const apiKey = user?.geminiApiKey;

  const prompt = `
  You are an expert academic coach and exam preparation planner. 
  Please create a highly detailed, personalized, and efficient study plan for a student based on the following:
  - Subject details and units to cover: "${subjectsUnits}"
  - Hard exam/completion deadline: "${deadline}" (Current date and time is ${new Date().toLocaleString()})

  Requirements for the plan:
  1. Act as a premium, highly encouraging AI coach.
  2. Structure the plan clearly using Markdown, including:
     - 🌟 A motivating title and overview.
     - 📅 A day-by-day or week-by-week calendar schedule from today until the deadline.
     - ⏱️ Specific hourly/block breakdowns for each unit.
     - 🧠 Strategic study techniques tailored for the subject (e.g., active recall, Feynman technique, Pomodoro intervals).
     - 🛑 Review cycles, buffer days, and a final checklist.
  3. Use emojis, clear bullet points, bold accents, and clean dividers to make it visually outstanding.
  4. End with an energetic and inspiring pep talk!
  `;

  if (apiKey) {
    try {
      console.log('[AI Service] Calling Google Gemini API to generate plan...');
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }]
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini API returned status ${response.status}: ${errorText}`);
      }

      const resData = await response.json();
      const planText = resData.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!planText) {
        throw new Error('Invalid or empty response format from Gemini API');
      }

      console.log('[AI Service] Successfully generated study plan via Gemini API.');
      return planText;
    } catch (error) {
      console.error('[AI Service] Error calling Gemini API:', error.message);
      // Fallback to offline plan generator
      return generateOfflinePlan(subjectsUnits, deadline, `Google Gemini API failed (${error.message})`);
    }
  } else {
    // Generate an offline, high-quality, simulated plan
    console.log('[AI Service] No Gemini API key provided. Generating offline study plan.');
    return generateOfflinePlan(subjectsUnits, deadline, 'Offline Local Scheduler');
  }
}

// Highly creative local fallback generator that creates a beautiful, custom study plan
function generateOfflinePlan(subjectsUnits, deadline, generatorSource) {
  const deadlineDate = new Date(deadline);
  const now = new Date();
  const timeDiff = deadlineDate - now;
  const daysRemaining = Math.max(1, Math.ceil(timeDiff / (1000 * 60 * 60 * 24)));

  const parsedUnits = subjectsUnits
    .split(/[\n,;]+/)
    .map(u => u.trim())
    .filter(u => u.length > 0);
  
  if (parsedUnits.length === 0) {
    parsedUnits.push('General Subject Syllabus');
  }

  let plan = ``;
  plan += `# 🚀 YOUR ULTIMATE AI STUDY PLAN\n\n`;
  plan += `*Generated by: **${generatorSource}** | ⏳ **${daysRemaining} Days** until your Exam/Deadline!*\n\n`;
  plan += `> "The secret of getting ahead is getting started." Let's crush this exam! Below is your custom-structured learning roadmap to guarantee success.\n\n`;
  
  plan += `## 📊 SYLLABUS TRACKING SUMMARY\n`;
  plan += `We have broken down your study material into the following high-priority segments:\n`;
  parsedUnits.forEach((unit, index) => {
    plan += `- **Segment ${index + 1}:** \` ${unit} \` 🎯 *(Priority: High)*\n`;
  });
  plan += `\n`;

  plan += `## 📅 THE DAILY PROGRESSIVE TIMELINE\n`;
  plan += `Here is your day-by-day study calendar customized for your target date of **${deadlineDate.toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}**:\n\n`;

  if (daysRemaining <= 3) {
    // Crunch schedule
    plan += `> ⚠️ **ALERT: CRUNCH TIME MODE ENGAGED (Short-Term Prep)**\n\n`;
    plan += `### **🔥 Day 1: Deep Absorption & Mapping**\n`;
    plan += `- **Morning:** Study **Segment 1** (${parsedUnits[0] || 'Core topics'}). Allocate 3 hours using the *Feynman Technique* (explain concepts to yourself in simple terms).\n`;
    plan += `- **Afternoon:** Attack **Segment 2** (${parsedUnits[1] || 'Secondary topics'}). Spend 3 hours, taking 10-minute breaks every 50 minutes (Pomodoro).\n`;
    plan += `- **Evening:** Formulate summary tables or active recall flashcards. No passive reading!\n\n`;

    plan += `### **🔥 Day 2: Advanced Blitz & Integration**\n`;
    parsedUnits.slice(2).forEach((unit, idx) => {
      plan += `- **Block A:** Power study **${unit}**. Core focus on standard formula sheets, key definitions, and active recall.\n`;
    });
    plan += `- **Practice session:** Spend 3 hours solving past papers or testing yourself using active-recall quizzes. Highlight weak sections.\n\n`;

    plan += `### **🏁 Day 3 (Final Stretch): Active Consolidation & Mock Exams**\n`;
    plan += `- **First Half:** Skim summary notes. Focus 100% on the weakest areas identified yesterday.\n`;
    plan += `- **Second Half:** Conduct a simulated exam under timed conditions. Stop studying 4 hours before bedtime to guarantee maximum rest.\n`;
  } else {
    // Multi-phase schedule
    const segmentCount = parsedUnits.length;
    const daysPerSegment = Math.max(1, Math.floor((daysRemaining - 2) / segmentCount));
    
    let currentDay = 1;
    parsedUnits.forEach((unit, idx) => {
      plan += `### **📚 Phase ${idx + 1}: Mastering "${unit}" (Days ${currentDay} - ${currentDay + daysPerSegment - 1})**\n`;
      plan += `- **Core Strategy:** Direct focus, active mapping, and concept breakdown.\n`;
      plan += `- **Day ${currentDay}:** Read and summarize primary theories, formulas, and diagrams. Create mind maps.\n`;
      if (daysPerSegment > 1) {
        plan += `- **Day ${currentDay + daysPerSegment - 1}:** Answer review questions, write summaries, and do lightweight active recall testing.\n`;
      }
      plan += `\n`;
      currentDay += daysPerSegment;
    });

    plan += `### **🔄 Phase ${segmentCount + 1}: Systemic Review & Mock Exams (Days ${currentDay} - ${daysRemaining - 1})**\n`;
    plan += `- Combine all chapters together. Solve past years' question papers under strict exam conditions.\n`;
    plan += `- Implement the **Spaced Repetition** method: review flashcards from Phase 1 and Phase 2 to reactivate long-term memory traces.\n\n`;

    plan += `### **🏆 Day ${daysRemaining} (The Night Before): Peak Mental State**\n`;
    plan += `- **Relaxation:** Light review of the "Quick Summary Sheets" for 2 hours maximum in the morning.\n`;
    plan += `- **Logistics:** Pack necessary supplies, water, and IDs. Get 8 hours of deep sleep. You are fully prepared!\n`;
  }

  plan += `\n`;
  plan += `## 🧠 ADVANCED STUDY COGNITIVE TACTICS\n`;
  plan += `1. **Active Recall:** Close your study source and explain the concept aloud from memory. This strengthens neural connections 10x faster than highlighting!\n`;
  plan += `2. **Pomodoro Technique:** Set a timer for 25 minutes of absolute focus, followed by a 5-minute movement break. Repeat 4 times, then take a long 20-minute rest.\n`;
  plan += `3. **Feynman Method:** Attempt to teach a complex unit to a hypothetical 10-year-old. Wherever you struggle to simplify, that is your knowledge gap! Go back and read that specific paragraph.\n`;
  plan += `\n`;

  plan += `## 🌟 COACH'S PEP TALK\n`;
  plan += `> *"Success is the sum of small efforts, repeated day in and day out."*\n`;
  plan += `> You have structured your syllabus, set a clear boundary, and mapped your progress. Every page you cover and every problem you solve brings you closer to your goal. Believe in your preparation, maintain discipline, and let's go get that **A+**! 🎓🔥\n`;

  return plan;
}
